#!/bin/sh
# neko-service: foreground
# neko-service: requires-fbdev
case "${1:-}" in
    run)
        case " $(cat /proc/cmdline) " in
            *' neko.x11=1 '*) exec /usr/bin/neko-x11-session --service ;;
        esac
        exec /usr/bin/neko-session
        ;;
    *) exit 2 ;;
esac
