[greeter]
background=/usr/share/backgrounds/nekoos/neko.svg
theme-name=Adwaita
icon-theme-name=Adwaita
font-name=DejaVu Sans 11
indicators=~host;~spacer;~clock;~spacer;~session;~language;~power
clock-format=%H:%M
